### ISSUE TITLE
add Schafer File support to BasicWorm

### ISSUE THREAD

**Issue by JimHokanson** [openworm/movement_validation#125]
BasicWorm was written without support for loading non-normalized worm data and it should be added in.

**Comment by JimHokanson** [comment]
@MichaelCurrie 

1. Why do we have head and tail attributes? What purpose do these serve?

2. From a design perspective, are we ok with having the same class having its attributes take on many different forms (i.e. skeleton no contour, contour no skeleton, ndarray vs list of ndarrays?

**Comment by MichaelCurrie** [comment]
1. Head and Tail attributes are so that we can accept data where head is not necessarily at the 0 index and tail is not necessarily at the -1 index.  After recent refactoring, BasicWorm no longer exists and instead the class encapuslating data in a general state without any head or tail assumptions is called GeneralizedSkeletonAndContour.  Then the points are ordered and we end up with OrderedSkeletonAndContour.  This class can then be transformed into a NormalizedWorm.

![image](https://cloud.githubusercontent.com/assets/5267078/7822525/58db880a-03b3-11e5-82c1-b9b87053a693.png)
