### ISSUE TITLE
non-equal feature comparisons in validate features should be an error

### ISSUE THREAD

**Issue by JimHokanson** [openworm/movement_validation#146]
Currently validate features is being used in our tests. However we are currently only testing that it runs, not that the comparisons are actually equal. We should run all of the comparisons and then throw an error at the end if any of them are not the same.

**Comment by MichaelCurrie** [comment]
I made sure it works by making the build fail with 480eea2e43e32028804d88e0ae2f3315e82f0aff.

Then I made it pass with 3dfde14a1325251ca1ab7f6e0c3aa387fa999d16 by fixing `posture.bends`, which didn't have an equality method and thus Posture was returning None which was interpreted as a fail since assert(None) throws an error.
